dictionaries:
    - en
    - en_GB

# Any files/folders we should ignore?
excluded_files:
    - ".github/.typo-ci.yml"
    - "node_modules/**/*"
    - "package-lock.json"

# Any typos we should ignore?
excluded_words:
    - fastify
    - fhir
    - hl7
    - nhs
    - ydh

# Would you like filenames to also be spellchecked?
spellcheck_filenames: true
