name: 🚀 Feature Request
description: Submit a proposal for a new feature
labels: [feature]

body:
    - type: markdown
      attributes:
          value: |
              Thanks for making a feature request, new ideas are greatly appreciated!

    - type: checkboxes
      id: prerequisites
      attributes:
          label: Prerequisites
          options:
              - label: I have written a descriptive title
                required: true
              - label: |
                    I have searched existing feature requests to ensure it has not already been proposed
                required: true
              - label: |
                    I agree to follow the [Code of Conduct](../../CODE_OF_CONDUCT.md) that this project adheres to
                required: true

    - type: textarea
      id: description
      attributes:
          label: Description
          description: A clear and concise description of what the feature is, and what it would solve.
      validations:
          required: true
