name: Spellcheck

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    spellcheck:
        name: Spellcheck with Typo CI
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2.3.4
            - name: TypoCheck
              uses: typoci/spellcheck-action@v0.4.0
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
